services:
  keycloak-db:
    image: postgres:16-alpine
    container_name: keycloak-postgres
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U keycloak"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - keycloak_data:/var/lib/postgresql/data
    networks:
      - application

  keycloak:
    image: quay.io/keycloak/keycloak:26.5
    container_name: keycloak
    command: start-dev --import-realm
    environment:
      KC_DB: postgres
      KC_DB_URL_HOST: keycloak-db
      KC_DB_URL_DATABASE: keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: password
      KC_HOSTNAME_STRICT: "false"
      KC_HTTP_ENABLED: "true"
      KC_HEALTH_ENABLED: "true"
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
    healthcheck:
      test: [ "CMD-SHELL", "exec 3<>/dev/tcp/127.0.0.1/8080" ]
      interval: 5s
      timeout: 5s
      retries: 10
    volumes:
      - ./keycloak-config:/opt/keycloak/data/import/
    ports:
      - "9090:8080"
    depends_on:
      keycloak-db:
        condition: service_healthy
    networks:
      - application

  listing-db:
    image: postgres:16-alpine
    container_name: listing-postgres
    environment:
      POSTGRES_DB: listing_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d listing_db"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - listing_data:/var/lib/postgresql/data
    networks:
      - application

  listing-service:
    build: ./Listing-Service
    container_name: listing-service
    ports:
      - "8081:8080"
    environment:
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI: http://localhost:9090/realms/handy-market
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI: http://keycloak:8080/realms/handy-market/protocol/openid-connect/certs

      SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_KEYCLOAK_CLIENT_ID: listing-service
      SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_KEYCLOAK_CLIENT_SECRET: nYM2Hs6O0BJVhWJ2viYoDoEVpXzqOyCn
      SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_KEYCLOAK_AUTHORIZATION_URI: http://localhost:9090/realms/handy-market/protocol/openid-connect/auth
      SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_KEYCLOAK_TOKEN_URI: http://keycloak:8080/realms/handy-market/protocol/openid-connect/token
      SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_KEYCLOAK_JWK_SET_URI: http://keycloak:8080/realms/handy-market/protocol/openid-connect/certs

      SPRING_DATASOURCE_URL: jdbc:postgresql://listing-db:5432/listing_db
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
    depends_on:
      listing-db:
        condition: service_healthy
      keycloak:
        condition: service_healthy
    networks:
      - application

volumes:
  keycloak_data:
  listing_data:

networks:
  application: