spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9090/realms/handy-market
          jwk-set-uri: http://host.docker.internal:9090/realms/handy-market/protocol/openid-connect/certs
      client:
        registration:
          keycloak:
            client-id: listing-service
            client-secret: nYM2Hs6O0BJVhWJ2viYoDoEVpXzqOyCn
            scope:
              - openid
              - profile
              - email
            authorization-grant-type: authorization_code
        provider:
          keycloak:
            issuer-uri: http://host.docker.internal:9090/realms/handy-market
            jwk-set-uri: http://host.docker.internal:9090/realms/handy-market/protocol/openid-connect/certs